version: '3.8'

services:
  nanovideo-api:
    build: .
    ports:
      - "8001:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DOWNLOADS_DIR=/app/downloads
      - API_KEYS=your-secure-api-key-here
      - ALLOWED_HOSTS=*
    volumes:
      # Mount downloads directory for persistence
      - ./downloads:/app/downloads
      # Mount logs if needed
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nanovideo-network

networks:
  nanovideo-network:
    driver: bridge
